import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { SideBar } from '@/components/app/layout/SideBar';
import { Header } from '@/components/app/layout/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
      </head>
      <body className={inter.className}>
        <div className="grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
          <SideBar />
          <div className="flex h-dvh flex-col">
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
